name: flutter_contacts
description: Flutter plugin to read, create, update, delete and observe native contacts on Android and iOS.
version: 0.0.5
homepage: https://github.com/QuisApp/flutter_contacts

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  diacritic: ^0.1.1
  json_annotation: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.4
  json_serializable: ^3.5.0

flutter:
  plugin:
    platforms:
      android:
        package: co.quis.flutter_contacts
        pluginClass: FlutterContactsPlugin
      ios:
        pluginClass: FlutterContactsPlugin
