name: flutter_contacts
description: Flutter plugin to read, create, update, delete and observe native contacts on Android and iOS, with vCard support
version: 0.2.0
homepage: https://github.com/QuisApp/flutter_contacts

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  diacritic: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.9.2
  test: ^1.15.7

flutter:
  plugin:
    platforms:
      android:
        package: co.quis.flutter_contacts
        pluginClass: FlutterContactsPlugin
      ios:
        pluginClass: FlutterContactsPlugin
